name: Dependabot_Workflow

on:
  schedule:
    - cron: '58 16 * * *'

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Action Checkout 
        uses: actions/checkout@v3
      - name: optimisation des dependances avec cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Action Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.13.1'
      - name: Action Dependabot
        uses: dependabot/dependabot-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
