name: Release_Workflow
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
     actions: write
     checks: write
     contents: write
     deployments: write
     id-token: write
     issues: write
     pull-requests: write
     repository-projects: write
     security-events: write
     statuses: write
    steps:
      - uses: actions/checkout@v3
      - name: Action Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: stable
      - name: Build and Release
        uses: goreleaser/goreleaser-action@v4
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: docker Setup QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build And Publish Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/super_calculator:${{  github.ref_name }}
